### ISSUE TITLE
Make network-wide notifications dismissal apply to all network

### ISSUE THREAD

**Issue by ykadosh** [askupasoftware/wp-admin-notification#1]
In a multisite environment, a dismissed network-wide notification should be removed from all sites.

**Comment by IvanRF** [comment]
I'm getting a `Fatal error: Class 'Amarkal\Admin\Notifications' not found in ...\wp-admin-notification\bootstrap.php on line 36` with the last changes

**Comment by ykadosh** [comment]
Are you using composer?

**Comment by IvanRF** [comment]
no, just a require_once on the bootstrap.php

**Comment by ykadosh** [comment]
What's your PHP version?

**Comment by IvanRF** [comment]
5.5.12

**Comment by ykadosh** [comment]
I'm unable to reproduce this. Any clue?

**Comment by ykadosh** [comment]
`bootstrap.php` has an if statement `if( !class_exists('Composer\\Autoload\\ClassLoader') )` to check if composer is being used, and if not, it will include all necessary files manually. Is there a reason why `if( !class_exists('Composer\\Autoload\\ClassLoader') )` would return `true` in your setup even though you are not using composer?

**Comment by IvanRF** [comment]
Yes, it is happening just that, the require_once 'Notifications.php'; is never reached

**Comment by ykadosh** [comment]
That would mean that you have a class named `Composer\Autoload\ClassLoader` in your environment?

**Comment by IvanRF** [comment]
😄 indeed I have, the Comment Mail plugin and at least 3 more plugins use that class

**Comment by IvanRF** [comment]
wow, I have at least 3 more plugins which use that class

**Comment by ykadosh** [comment]
Hmmm... I guess they are using composer internally. In that case I will have to find a safer way to check if composer is being used.

**Comment by IvanRF** [comment]
yes, maybe just check for your specific class

**Comment by ykadosh** [comment]
Yes but then there would be no point in using composer, since all the files will be included manually regardless, even if they are not being used (since that statement will always return false).

**Comment by ykadosh** [comment]
See #7
