### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by IvanRF** [askupasoftware/wp-admin-notification#4]
Could you provide an example on how to use this library?

Since I have conditions before showing a `notice`, I added the calls to `wp_admin_notification` in the `current_screen` hook. However, dismissed notices are still shown.

**Comment by ykadosh** [comment]
Sure, can you post your code?

**Comment by IvanRF** [comment]
```
function grd_admin_notices( $current_screen ) {
	if (!current_user_can( 'manage_options' ))
		return;
		
	require_once( GRD_PLUGIN_DIR  . 'includes/wp-admin-notification/bootstrap.php' );
	
	// Check if current screen is my Settings page
	global $grd_admin_page;
    $is_admin_page = ( $current_screen->id == $grd_admin_page );
	
	if (!$is_admin_page) {
		$link = get_settings_link( __( 'GitHub Release Downloads Settings', 'github-release-downloads' ) );
		$msg = sprintf( __( 'Go to %s to set default values, an access token and get help.', 'github-release-downloads' ), $link );
		wp_admin_notification('grd_notice_settings', $msg, 'success', true);
	}
	
	if ($is_admin_page && !get_option('grd_token')) {
		$msg = __( 'Generate an access token to avoid rate limiting on the GitHub API.', 'github-release-downloads' );
		wp_admin_notification('grd_notice_token', $msg, 'error');
	}
}
add_action( 'current_screen', 'grd_admin_notices' );
```

**Comment by IvanRF** [comment]
I'm doing some testing right now, and on the `init()` function `$this->dismissed_notices = get_option('wp_dismissed_notices');` is always `false`. I will check if the AJAX section is saving the dismiss

**Comment by ykadosh** [comment]
Hmmm... I'm able to reproduce this. It looks like a bug. Looking into it now.

**Comment by IvanRF** [comment]
It seems that the AJAX action only works if it is added before the hook I'm using. I refer to: `add_action( 'wp_ajax_dismiss_admin_notification', array( $this, 'dismiss_notification' ) );`

What could be useful is to add a callback function as a parameter for `wp_admin_notification`. This callback can be used as a precondition to render or not some notification, and it will be called in the `admin_notices` hook, which is your `render_notification` function.

**Comment by IvanRF** [comment]
In my case, I show a specific notification when the user is in the settings page of the plugin. The callback parameter will allow me to make that check.

**Comment by ykadosh** [comment]
Yes, you're correct. the `current_screen` action is triggered too late for the `wp_ajax` action to hook properly. Outside this action it works fine.

Your solution can work, but i'm thinking that `wp_admin_notification` should work inside any action hook without problems to prevent future issues like this. Perhaps I should hook the `wp_ajax_dismiss_admin_notification` action as part of the bootstrapping process.

**Comment by IvanRF** [comment]
Yes, calling the AJAX hook outside the `init()` function should solve it too.

**Comment by ykadosh** [comment]
The only issue I can think of with my approach is that calling the `init` as part of the bootstrapping process will register all the hooks even if there are no registered notifications. I think your approach will be better in that sense.

**Comment by IvanRF** [comment]
I didn't test it, but what if the only call that you include in the bootstrapping process is the `add_action( 'wp_ajax_dismiss_admin_notification', array( $this, 'dismiss_notification' ) );`?

**Comment by IvanRF** [comment]
I think there is another root issue with the library. I'm testing a basic code (outside any hook):
```
require_once( GRD_PLUGIN_DIR  . 'includes/wp-admin-notification/bootstrap.php' );
wp_admin_notification('example', "Hello", 'success', true);
```
and the notification is always showing.

**Comment by ykadosh** [comment]
Yes, it can work. I'll push a fix soon.
